version: '3.8'

services:
  # --- BASE DE DATOS RELACIONAL MULTIDOMINIO ---
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mapea la carpeta completa (incluyendo el script .sh y la subcarpeta sql)
      - ./init_db:/docker-entrypoint-initdb.d/
    restart: always

  # --- BASE DE DATOS SERIES DE TIEMPO (Telemetría de los Sensores) ---
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb_container
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: always

volumes:
  postgres_data:
  influxdb_data:
  influxdb_config: